version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # project root (where pyproject.toml and uv.lock live)
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
